version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: drs_db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"

  redis_cache:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  main_server:
    build: ./server
    container_name: main_server
    depends_on:
      - mysql_db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql_db
      - DB_NAME=drs_db
      - DB_USER=root
      - DB_PASSWORD=1234

  quiz_service:
    build: ./quiz_service
    container_name: quiz_service
    depends_on:
      - mongo_db
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/
      - MAIN_SERVER_URL=http://main_server:5000

  client:
    build: ./client
    container_name: react_client
    ports:
      - "5173:5173"
    depends_on:
      - main_server
